### ISSUE TITLE
Can detect raids but does not attempt to join

### ISSUE THREAD

**Issue by Drangsama** [Masuzu/SarasaBot#38] opened 2018-01-06 17:29 UTC
Hello, I've been using Sarasabot for a bit now and most of the time it has been working well, but when I tried to switch to my desktop today, it would detect the raid but not join. I was wondering if I did something wrong.
Things I've tried: Redownloading Sarasabot, Disabling firewall, Reloading Sarasabot, Disable/Enable Viramate

Thanks 😸 
![default](https://user-images.githubusercontent.com/35174373/34642184-d81b81a4-f2c3-11e7-9f3b-1f4c498f32da.PNG)

**Comment by Masuzu** [comment] 2018-01-10 14:18
Hello,
Unfortunately I am not sure how to reproduce it as it seems to be a first of its kind.
Closing it as seems too isolated.

**Closed by Masuzu** 2018-01-10 14:18 UTC
