### ISSUE TITLE
BUG:  BOT ALARM FOR ONLY 1 SECOND

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/SarasaBot#177] opened 2018-05-27 04:36 UTC
As the title said, the bot sounded for only a sec and stopped sounding, please fix this asap, this is actually criticle

**Comment by Zir1984** [comment] 2018-05-28 00:56
I have the same happen every time, zoey works fine, but sarasa just procs the alarm laugh and before the jikan da closes itself. Had it happen 4 times in a row already

**Comment by Ohwhat00** [comment] 2018-05-28 22:45
Bump for this, experiencing the same issue.  Can't leave the bot unattended due to this.

**Comment by CorrinKrow** [comment] 2018-06-02 23:00
have the same issue as well

**Comment by Masuzu** [comment] 2018-06-05 08:28
I could not reproduce the issue on my side after a catpcha screen was displayed during the party selection confirmation.
The default ini file has `NumNotifications` set to 9999.

**Comment by Masuzu** [comment] 2018-06-06 14:10
Actually I spotted a potential cause leading to this observation.
It is not fixed in v1.9.9.

**Closed by Masuzu** 2018-06-06 14:10 UTC
