### ISSUE TITLE
Both bots have same ID by default

### ISSUE THREAD

**Issue by agesa** [Masuzu/SarasaBot#7] opened 2017-12-03 01:44 UTC
While ZooeyBotExtensionIdGenerator.exe solves everything, anyone who hasn't run that once will probably be confused for a few minutes when loading one extension into Chrome overwrites the other one.  Is it possible to give them different default IDs?

**Comment by Masuzu** [comment] 2017-12-04 10:58
I can't reproduce the issue.
I can load both extensions and each has a different ID. There is no such thing as a default ID.

**Comment by Masuzu** [comment] 2017-12-04 22:25
Addressed in v1.2.0: https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-2-0
Thank you again for reporting this issue.

**Closed by Masuzu** 2017-12-04 22:25 UTC
