### ISSUE TITLE
Sarasabot doesnt access one punch.lua

### ISSUE THREAD

**Issue by shiraseo** [Masuzu/SarasaBot#137] opened 2018-04-02 09:06 UTC
Hello, after I update my sarasabot it doesnt access one punch.lua. so when the party enter the battle the bot just terminated the battle. It doesnt use skills which I have set in the lua file. And I am pretty much sure that my script is good. The script is fine in sarasabot v1.7.12. Please help.

**Comment by devvah** [comment] 2018-04-02 13:50
I've noticed that too, that when script is very short bot will just reload raid right after entering and then terminate battle without doing anything written in script.

**Comment by shiraseo** [comment] 2018-04-02 14:35
So, when the script is 'long' enough the bot is doing fine and cant access the script?

**Comment by Nanam1nnnn** [comment] 2018-04-03 00:24
The same. It just join a raid and do nothing to search the next raid.
My chrome version is 64.
The file works well before, I just changed the raid which the bot search for in the .ini, but I didn't change the .lua file. And It can search, it can join, but it can not use skill or attack.

**Comment by YumeHaru** [comment] 2018-04-03 06:51
It seems we've same bug that I reported, too.

**Comment by gary173** [comment] 2018-04-04 00:40
Me too
It just join a raid and find  next raid.
Please help me

**Comment by devvah** [comment] 2018-04-04 09:02
Actually I was wrong, after few test it seems you need to edit script line in .ini every time before launching bot or it will not detect script even if it worked previously.

**Comment by shiraseo** [comment] 2018-04-04 09:30
Actually the bot is working again after I reinstall the chrome. So everything is back to normal again. Beside the solution from devvah, you can try to reinstall the chrome to solve this issue. Hope it works for you too.

**Comment by Extr736** [comment] 2018-04-04 15:28
I have the same issue. It hasn’t worked for me once and I can’t seem to download the older versions to test either.

**Comment by YumeHaru** [comment] 2018-04-04 22:08
I had to revert back to 1.7 to make the bot works.

**Comment by Masuzu** [comment] 2018-04-07 21:03
Hello,
The script being loaded is displayed in the console. Sometimes you may need to switch the encoding of your Lua script as well or its contents may be ignored depending on your Windows locale settings.
I use UTF8 on my two computers, one of which has Janapese Windows locale settings and the other one English Windows locale settings.

**Comment by devvah** [comment] 2018-04-07 22:57
This is definitely bug introduced in recent Sarasa bot while Zooey bot works no problem. I'm using Visual Studio Code for everything with UTF-8 without BOM (checked every script and ini - all use the same) encoding and sharing most scripts between 2 bots so there should be no disparity that Sarasa bot requires constant modifying of ini to make script work while Zooey does daily magnas with the same script past 2 months without needing to edit ini before every launch.

I will see how 1.8.11 fares and edit this post.

**Comment by kisame21** [comment] 2018-04-09 07:45
im still having the same problem and idk how to fix it. i tried reinstalling chrom63 and still it doesnt work

**Comment by kisame21** [comment] 2018-04-09 08:03
@shiraseo what version of chrome are you running?

**Comment by abc123129** [comment] 2018-04-10 09:07
similar issues, though it sometimes work and sometimes doesn't, seems to be a matter of luck of the draw. 
it is quite frustrating to realize that sometimes when you start the bot it works but after some auto-pilot it will just randomly stop working and stops accessing the script for reasons unknown. another situation is that it just won't work until you restart the bot several times and it suddenly happen to work.
if a fix is not possible, maybe at least provide us with download links to the previous versions.
this seems to a big issue that a lot of people are having and since the license expires every week, i think some kind of solution should be offered (I am halfway through the week and barely got this to work most of the time).
i am using chromium 67.0.3394.0 by the way but it doesn't seem to matter which version you use as this problem persists regardless of versions.

**Comment by Nanaya8** [comment] 2018-04-10 10:38
Same problem here,  it somehow worked when I ran it for the first time, now it suddenly stopped using the script.

**Comment by kisame21** [comment] 2018-04-10 10:55
mine never worked since i got it :(

**Comment by thebp2** [comment] 2018-04-11 11:56
Having the same problem. The exact same SarasaBot.ini and lua script works on 1.7.12 but does not on 1.8.0 or 1.8.1. On 1.8.0 and 1.8.1 the using lua script line never shows up.

**Comment by thebp2** [comment] 2018-04-11 12:47
Maybe due to not having new ini file parameters for 1.8.0 in the ini file? Can't test this theory right now.

**Comment by Extr736** [comment] 2018-04-13 22:29
Issue was not addressed and my license expired. Really hope the license gets a bit more lienient at some point to help account for these issues, I’m super disappointed.

**Comment by devvah** [comment] 2018-04-14 01:46
The issue was actually addressed in [#139](https://github.com/Masuzu/SarasaBot/issues/139#issuecomment-381060700) and I can confirm that changing this parameter to 30000 solves that issue.

**Comment by Masuzu** [comment] 2018-04-14 09:52
All good then!

**Closed by Masuzu** 2018-04-14 09:52 UTC
Labels: bug
