### ISSUE TITLE
Bot stops moving early

### ISSUE THREAD

**Issue by Kakyu** [Masuzu/SarasaBot#113] opened 2018-03-21 01:58 UTC
My bot works great up until like 5 minutes when it starts to gargle and stops at the "pending battles screen" , on the console it just repeats "failed to join raid" or something close. 
Do I have to change a setting? I tried to turn on "force raid reward collection" but that didn't fix it. 

Is there some easy fix that I'm missing?

**Comment by LordShade** [comment] 2018-03-21 03:28
if you are using it to join event raids like the current Corrow, there is no proper event raid support as of yet so the bot just gargles with a ton of failed raid joins until one of them completes
I've yet to see it get stuck on the pending battles screen, but I've seen it pause on the results screen, the normal raid screen and sometimes on the raid collection screen. It appears to still be working however.
A good way to check is its still working is to navigate back to the Event tab on raids and see if you got 3 battles currently running. That will explain the failed to join raids, at least.

**Comment by Kakyu** [comment] 2018-03-21 04:04
Got it to work by switching fastraidrewardcollection to false and forceraidcollection to true, at least its been going for an hour.

**Comment by Masuzu** [comment] 2018-03-21 15:34
Hello,
If the raid collection does not work with `forceraidcollection=false`, it is very likely caused by a recent change with Chrome v65. https://github.com/Masuzu/ZooeyBot/issues/625
Otherwise you did well to report this issue, it might have to do with something I could fix on my side.

**Comment by Masuzu** [comment] 2018-03-31 18:36
Closing as it was most likely due to a Chrome version incompability, which is now checked during the initialization.

**Closed** 2018-03-31 18:36 UTC
