### ISSUE TITLE
The bot will stop when ahead party member comes out

### ISSUE THREAD

**Issue by kusyarudaora123** [Masuzu/SarasaBot#155] opened 2018-04-27 11:37 UTC
Hello.
Sarasabot came to stop at the moment when a party member died and a prepause character appeared.
I was able to use it normally until yesterday, but today this error has come to come out today.
Did something change in today's update?
![default](https://user-images.githubusercontent.com/36522930/39360820-aa1fb5e2-4a5a-11e8-9543-e53994ca7446.png)

**Comment by Masuzu** [comment] 2018-04-27 12:34
Hello,
I took note of the issue. I can't say for sure for now as having a front line character fall is not a rare occurrence and I got it happen while using Sarasa Bot as well.
Adding back other messages in a future release to find out the cause would help.

**Comment by Masuzu** [comment] 2018-04-28 11:02
Update: this is linked to https://github.com/Masuzu/ZooeyBot/issues/769
A patch is on the way.

**Comment by Masuzu** [comment] 2018-04-28 11:11
This is now addressed in https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-8-5

**Closed by Masuzu** 2018-04-28 11:11 UTC
Labels: bug
